-- =====================================================================
--  Koperasi — Skema PostgreSQL untuk Supabase
--  Hasil konversi dari MySQL (if0_38786425_kusahala.sql)
--  Jalankan file ini di Supabase: Dashboard > SQL Editor > New query > Run
-- =====================================================================

-- Hapus tabel lama bila ada (urut sesuai dependensi FK)
drop table if exists detail_pesanan cascade;
drop table if exists pesanan        cascade;
drop table if exists laporan        cascade;
drop table if exists recent         cascade;
drop table if exists barang         cascade;
drop table if exists pegawai        cascade;

-- ---------------------------------------------------------------------
-- pegawai
-- ---------------------------------------------------------------------
create table pegawai (
  id   integer generated by default as identity primary key,
  nama varchar(100)
);

-- ---------------------------------------------------------------------
-- barang
-- ---------------------------------------------------------------------
create table barang (
  id         integer generated by default as identity primary key,
  nama       varchar(100),
  harga_jual integer,
  harga_beli integer not null default 0,
  deskripsi  text,
  gambar     varchar(255)            -- path file di Supabase Storage (bucket "barang")
);

-- ---------------------------------------------------------------------
-- pesanan
-- ---------------------------------------------------------------------
create table pesanan (
  id         integer generated by default as identity primary key,
  pegawai_id integer references pegawai(id) on delete set null,
  tanggal    timestamptz default now()
);

-- ---------------------------------------------------------------------
-- detail_pesanan
-- ---------------------------------------------------------------------
create table detail_pesanan (
  id         integer generated by default as identity primary key,
  pesanan_id integer references pesanan(id) on delete cascade,
  barang_id  integer references barang(id)  on delete set null,
  kuantitas  integer default 1,
  catatan    text not null default ''
);

-- ---------------------------------------------------------------------
-- laporan (snapshot hasil "Generate Laporan")
-- ---------------------------------------------------------------------
create table laporan (
  id               integer generated by default as identity primary key,
  bulan            integer not null,
  tahun            integer not null,
  nama_pegawai     varchar(100) not null,
  nama_barang      varchar(100) not null,
  harga_beli       integer not null default 0,
  harga_jual       integer not null default 0,
  total_harga_beli integer not null default 0,
  total_harga_jual integer not null default 0,
  keuntungan       integer not null default 0,
  generate_ke      integer not null default 1,
  created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- recent (juara belanja per pegawai/barang) — opsional
-- ---------------------------------------------------------------------
create table recent (
  id              integer generated by default as identity primary key,
  id_pegawai      integer not null,
  id_barang       integer not null,
  total_pembelian integer not null,
  updated_at      timestamptz not null default now()
);

create index idx_pesanan_tanggal      on pesanan (tanggal);
create index idx_pesanan_pegawai      on pesanan (pegawai_id);
create index idx_detail_pesanan_pid   on detail_pesanan (pesanan_id);
create index idx_detail_pesanan_bid   on detail_pesanan (barang_id);
create index idx_laporan_periode      on laporan (bulan, tahun, generate_ke);

-- =====================================================================
--  ROW LEVEL SECURITY (RLS)
--  PENTING: karena tidak ada server PHP lagi, kunci "anon" Supabase
--  ikut terlihat di browser. RLS-lah yang melindungi data Anda.
--
--  Konfigurasi di bawah ini = MODE TERBUKA (semua orang boleh baca &
--  tulis). Ini meniru perilaku aplikasi PHP lama Anda yang tanpa login.
--  Cocok untuk uji coba / pemakaian internal.
--
--  >>> Untuk produksi, lihat catatan di README untuk mengunci akses
--      tulis (insert/update/delete) hanya untuk user yang login. <<<
-- =====================================================================
alter table pegawai        enable row level security;
alter table barang         enable row level security;
alter table pesanan        enable row level security;
alter table detail_pesanan enable row level security;
alter table laporan        enable row level security;
alter table recent         enable row level security;

-- Helper: buat policy "boleh semua" untuk anon & authenticated
do $$
declare t text;
begin
  foreach t in array array['pegawai','barang','pesanan','detail_pesanan','laporan','recent']
  loop
    execute format('create policy "%s_select" on %I for select using (true);', t, t);
    execute format('create policy "%s_insert" on %I for insert with check (true);', t, t);
    execute format('create policy "%s_update" on %I for update using (true) with check (true);', t, t);
    execute format('create policy "%s_delete" on %I for delete using (true);', t, t);
  end loop;
end $$;
